---
- name: demo lookups
  hosts: local

  tasks:
    - name: lookup of a csv file
      debug: msg="{{ lookup('file','gamma.csv') }}"


    - name: dd
      debug: var=msg
    - name: we could use file direclty, but this shows output from command
      debug: msg="{{ item }} is a line running cat on /etc/motd"
      with_lines: cat gamma.csv
